format:
  _help_disable:
    - Disable formatting entirely, making cmake-format a no-op
  disable: false
  _help_line_width:
    - How wide to allow formatted cmake files
  line_width: 80
  _help_tab_size:
    - How many spaces to tab for indent
  tab_size: 2
