name: Ros build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: foxy
      - name: build
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: simple_thread_tester
          target-ros2-distro: foxy
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: DoozyX/clang-format-lint-action@v0.16.1
        with:
          source: '.'
          extensions: 'cc'
          style: '.clang-format'
          clangFormatVersion: '10'
          check-path: '.'